-- Store VdoCipher connection status per user
create table if not exists public.vdocipher_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  connected boolean not null default true,
  last_verified timestamptz not null default now(),
  account_info jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vdocipher_connections_user_unique unique (user_id)
);

alter table public.vdocipher_connections enable row level security;

create policy vdocipher_connections_select on public.vdocipher_connections
  for select to authenticated using (user_id = auth.uid());

create policy vdocipher_connections_insert on public.vdocipher_connections
  for insert to authenticated with check (user_id = auth.uid());

create policy vdocipher_connections_update on public.vdocipher_connections
  for update to authenticated using (user_id = auth.uid());

create policy vdocipher_connections_delete on public.vdocipher_connections
  for delete to authenticated using (user_id = auth.uid());

create or replace function public.set_updated_at_vdocipher_connections()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_updated_at_vdocipher_connections on public.vdocipher_connections;
create trigger set_updated_at_vdocipher_connections
before update on public.vdocipher_connections
for each row execute function public.set_updated_at_vdocipher_connections();

